### ISSUE TITLE
Log scale is not working in the mortality rate evolution

### ISSUE THREAD

**Issue by fredericlam** [fredericlam/IarcDataVisualization#2]
It is probably due to the update on the counter.

**Comment by fredericlam** [comment]
@timat35 I think it's on my side. Let me check.

**Comment by timat35** [comment]
ah mince je viens de le corriger aussi...

**Comment by timat35** [comment]
tu as etait plus rapide par contre :)

**Comment by timat35** [comment]
je m'occupe du nouveau conflit

**Comment by timat35** [comment]
c'est bon.. (j'aurais du reouvrir le truc mais bon.. je vois le principe pour la prochaine fois)
